### ISSUE TITLE
Error when executing

### ISSUE THREAD

**Issue by RoelandSalij** [mendix/mx-check-deprecations#3]
C:\Users\AppData\Roaming\npm\node_modules\mx-check-deprecations\lib\checker.
js:129
                var ext = path.parse(file)['ext'];
                               ^
TypeError: Object #<Object> has no method 'parse'
    at C:\Users\AppData\Roaming\npm\node_modules\mx-check-deprecations\lib\c
hecker.js:129:18
    at arrayFilter (C:\Users\AppData\Roaming\npm\node_modules\mx-check-depre
cations\node_modules\lodash\index.js:1384:13)
    at Function.filter (C:\Users\AppData\Roaming\npm\node_modules\mx-check-d
eprecations\node_modules\lodash\index.js:6309:14)
    at Object.checkFiles (C:\Users\AppData\Roaming\npm\node_modules\mx-check
-deprecations\lib\checker.js:128:16)
    at Object.<anonymous> (C:\Users\AppData\Roaming\npm\node_modules\mx-chec
k-deprecations\cli.js:63:13)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)

**Comment by JelteMX** [comment]
This was due to having a very old version of Node. When we updated it to v4.2.3 LTS the error was gone. Updated the README

**Comment by RoelandSalij** [comment]
Thanks!
